# This is a config for E2B sandbox template.
# You can use 'template_id' (pdi0tao93djadqdrcc44) or 'template_name (html-developer) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='html-developer')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'html-developer' })

team_id = "077ad7dc-d362-43ae-8721-dd2551807e27"
dockerfile = "e2b.Dockerfile"
template_name = "html-developer"
template_id = "pdi0tao93djadqdrcc44"
